version: '2'

services:
  web:
    container_name: "curso-web-moderno-cod3r" 
    build: .
          #image: nikolaik/python-nodejs:python2.7-nodejs12-alpine 
    volumes:
      - .:/app
    working_dir: /app 
    entrypoint: /bin/sh -c "yarn install && yarn run start-dev"
    ports:
      - 1234:1234
